name: Francis Borja
markdown: kramdown
permalink: /:title
paginate: 5
excerpt_separator: <!--excerpt-->
paginate_path: "/blog/page-:num"
include: ["_pages"]

# google analytics
google_analytics: UA-84144727-2
google_site_verification: iLcn0SOTj8DwWZ4p_P_h3J_lxE8i1ZikWIx4lthZuCY

# seo
title: Francis Borja
description: Hello. My name is Francis and Francis means freedom.
logo: /assets/logomark-color.png

# social
social:
  links:
    - https://twitter.com/freeingfrancis
    - https://instagram.com/freeingfrancis

url: https://francisborja.com
enforce_ssl: francisborja.com

# post defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


# twitter cards
twitter_username: freeingfrancis
site_username: freeingfrancis
creator_username: freeingfrancis

# sass
sass:
  style: expanded
  deploy_style: compressed
  sass_dir: css



plugins:
- jekyll
- activesupport
- github-pages-health-check
- html-pipeline
- jekyll-avatar
- jekyll-coffeescript
- jekyll-default-layout
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-mentions
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-redirect-from
- jekyll-relative-links
- jekyll-sass-converter
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-swiss
- jekyll-theme-architect
- jekyll-theme-cayman
- jekyll-theme-dinky
- jekyll-theme-hacker
- jekyll-theme-leap-day
- jekyll-theme-merlot
- jekyll-theme-midnight
- jekyll-theme-minimal
- jekyll-theme-modernist
- jekyll-theme-primer
- jekyll-theme-slate
- jekyll-theme-tactile
- jekyll-theme-time-machine
- jekyll-titles-from-headings
- jemoji
- kramdown
- liquid
- listen
- minima
- nokogiri
- rouge
- ruby
- safe_yaml
- sass
- sassc
- guard-livereload
- guard-jekyll
